### ISSUE TITLE
Compiling on windows adds `#!/usr/bin/env php` to the output

### ISSUE THREAD

**Issue by c33s** [box-project/box#168]
```
php build/puppet-enc.phar foo.example.com --env=prod --file=nodes.yaml.dist
#!/usr/bin/env php
---
parameters:
    customer: example
    role_enc: undef
environment: development
```

<details>
>summary>box.yaml</summary>
 
 ```yaml
files:
    - composer.json
directories:
    - bin
    - config
    - src
    - lib
finder:
    -
      name: '*.*'
      in: vendor
      exclude:
        - .gitignore
        - .md
        - phpunit
        - Tester
        - Tests
        - tests
compactors:
    - Herrera\Box\Compactor\Json
    - Herrera\Box\Compactor\Php
compression: GZ
main: bin/puppet-enc
output: build/puppet-enc.phar
stub: true
git-commit: git_commit
git-version: git_version
git-tag: git_tag
chmod: '0755'

 ```
</details>
